### ISSUE TITLE
Name collision with `glib2`

### ISSUE THREAD

**Issue by traxys** [Byron/git-oxide#4]
I'm not really sure what can be done, maybe add a warning, but `gio` collides with an executable from `glib2`, I don't know for other linux distributions, but on Arch it's pretty much impossible to not install `glib2`.

**Comment by Byron** [comment]
Thanks a lot for letting me know!
I wasn't aware, and so happy that something as nice as `gio` is still available.

I think then I will go for `gix` as it's nice too. I do consider `gir` (for 'r'ust), but realized that my own muscle memory rather wants to type 'git' all the time :D.

If you have alternatives or ideas, or would like to let me know your preference between `gix` or `gir`, please do share :).

**Comment by traxys** [comment]
I used `giox` for disambiguation, but that is more than three letters, I think I prefer `gix` it's further from `git`, less risk to confuse. Though I am terrible at naming things

**Comment by Byron** [comment]
It's now called `gix` and `gixp` respectively - let's see how long it lasts ;).
Thanks again for bringing it up early, much appreciated.

**Comment by U007D** [comment]
FWIW I was expecting/wondering if I'd see `go` ;) or `gitox`...
.
